{
  "comments": [
    {
      "key": {
        "uuid": "9a629dbe_cd13695b",
        "filename": "zuul/ansible/library/zuul_afs.py",
        "patchSetId": 2
      },
      "lineNbr": 97,
      "author": {
        "id": 4146
      },
      "writtenOn": "2016-11-07T22:45:25Z",
      "side": 1,
      "message": "Since your command is already invoking bash do you need to set shell\u003dTrue here?\n\nAlso check_output can raise CalledProcessError, perhaps we should wrap this in a try/except and add return code info to output as well? Then in module.exit_json() below we can be a bit more specific about whether or not things have succeeded.",
      "revId": "33a74ef51c8b0aefa2334a053b5105a04e8aa4f9",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a629dbe_6d16b456",
        "filename": "zuul/ansible/library/zuul_afs.py",
        "patchSetId": 2
      },
      "lineNbr": 97,
      "author": {
        "id": 1
      },
      "writtenOn": "2016-11-08T17:01:31Z",
      "side": 1,
      "message": "Well, the whole thing is a string that ends up getting formatted.  I could reconfigure it like that, but this was a pretty straightforward port from the ansible form we used before, so I\u0027d just as soon leave it.  Even if I did change it, only the k5start would be passed in as argv, the bulk of the command would still be a shell blob, so it\u0027s not much of a win.\n\nAnd yes, we should do something with return codes here.",
      "revId": "33a74ef51c8b0aefa2334a053b5105a04e8aa4f9",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a629dbe_f1dd3e43",
        "filename": "zuul/ansible/library/zuul_afs.py",
        "patchSetId": 2
      },
      "lineNbr": 97,
      "author": {
        "id": 1
      },
      "writtenOn": "2016-11-08T17:09:02Z",
      "side": 1,
      "message": "Actually, I just tested this with a failure, and I\u0027m happy with the output that we get from Ansible.  We will get the full traceback of the CalledProcessError, along with the command it tried to run (which will include enough information to determine which subpath this failed on if that\u0027s the case) along with the exit code.  And Ansible will report the task as failed.",
      "revId": "33a74ef51c8b0aefa2334a053b5105a04e8aa4f9",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}